version: '3.8'

services:
  id3w-nextjs-app:
    image: node:20.10.0-alpine3.18
    container_name: id3w-nextjs-app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db

  db:
    image: 'postgres:15-alpine'
    container_name: postgres-db
    ports:
      - "54320:5432"
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=id3w
    volumes:
      - ./.postgres/data:/var/lib/postgresql/data

volumes:
  postgres_data:
