version: '3'
services:
  pg:
    image: 'postgres:15-alpine'
    restart: always
    environment:
      - POSTGRES_PASSWORD=dev-password
      - POSTGRES_DB=id3w
    ports:
      - '54320:5432'
    volumes:
      - ./.postgres/data:/var/lib/postgresql/data
